### ISSUE TITLE
Mobile first eerste versie

### ISSUE THREAD

**Issue by Shannafdnd** [TomDeeterink1/the-startup-responsive-interactieve-website#1]
Tops:
- Ziet er goed uit, goeie visuele hierarchie.
- Goeie semantische code
- Goed de huisstijl gebruikt in de code
- Duidelijke comments

Tips:
- Bij sommige vacatures kan je stukjes tekst over het team vinden, je kan kijken of je daar iets over kan vinden.

**Comment by TomDeeterink1** [comment]
Dit is doorgevoerd in de nieuwe versie.
